### ISSUE TITLE
Broken macOS lima example

### ISSUE THREAD

**Issue by caenrigen** [sylabs/singularity#3662]
**Type of issue**

macOS install `lima` example broken

**Description of issue**

After following https://docs.sylabs.io/guides/4.3/admin-guide/installation.html#mac `singularity` command is not available:

```bash
[victor@lima-singularity-ce log]$ singularity run library://alpine
bash: singularity: command not found

[victor@lima-singularity-ce log]$ sudo cat /var/log/cloud-init-output.log | grep -i "epel"
+ dnf -y install --enablerepo=epel singularity-ce squashfs-tools-ng
Error: Unknown repo: 'epel'
```

**Solution**

```yaml
provision:
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail

    dnf install -y epel-release # <--------------------
    dnf install -y singularity-ce squashfs-tools-ng # <-----------------
```

I will make a PR
