### ISSUE TITLE
Unable to use a custom cni network

### ISSUE THREAD

**Issue by scicco** [sylabs/singularity#959]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$> singularity --version
singularity version 3.7.1
```

**Describe the bug**
Hello, I'm unable to use a custom cni network using CNI static plugin. I think my cni static configuration is wrong. 

I'm using Ubuntu inside Virtualbox.

**To Reproduce**

cni configuration files:
```
$> ls /usr/local/etc/singularity/network
-rw-r--r-- 1 root root  601 Aug 31 07:54 00_bridge.conflist
-rw-r--r-- 1 root root  534 Aug 29 08:49 10_ptp.conflist
-rw-r--r-- 1 root root  513 Aug 29 08:49 20_ipvlan.conflist
-rw-r--r-- 1 root root  515 Aug 29 08:49 30_macvlan.conflist
-rw-r--r-- 1 root root  539 Aug 29 08:49 40_fakeroot.conflist
-rw-r--r-- 1 root root  589 Aug 31 08:29 50_static.conflist
```

```
$> cat /usr/local/etc/singularity/network/00_bridge.conflist
```

```yaml
{
    "cniVersion": "0.4.0",
    "name": "bridge",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "sbr0",
            "isGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.22.0.0/16",
                "routes": [
                    { "dst": "0.0.0.0/0" }
                ]
            }
        },
        {
            "type": "firewall"
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
```

```
$> cat /usr/local/etc/singularity/network/50_redis.conflist 
```

```yaml
{
  "cniVersion": "0.4.0",
  "name": "static-redis",
  "plugins": [
    {
      "type": "static",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.20.12/32",
            "gateway": "192.168.20.254"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    },
    {
      "type": "firewall"
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
    }
  ]
}
```

the rest of config are default

listing local files:
```
$> ls -lrt
-rwxr-xr-x 1 vagrant vagrant       48 Aug 26 07:15 env-file.sh*
-rw-r--r-- 1 vagrant vagrant      248 Aug 26 07:15 redis.def
-rwxr-xr-x 1 vagrant vagrant 40124416 Aug 29 14:59 redis.sif*
```

showing file contents:
```
$> cat redis.def
BootStrap:docker
From:redis:latest

%startscript
    # Important - you need to run this in the container to get the envar
    redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}

%runscript
    exec /usr/local/bin/docker-entrypoint.sh "$@"
```

```
$> cat env-file.sh
export REDIS_PASSWORD=ThisIsNotAStrongPassword!
```

checking network list **before** running singularity command:
```
$> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:e5:1b:70:f4:63 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 85946sec preferred_lft 85946sec
    inet6 fe80::e5:1bff:fe70:f463/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:01:93:68 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.222/24 brd 192.168.111.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe01:9368/64 scope link
       valid_lft forever preferred_lft forever
```

```
$> whoami
root
```

running command:
```
singularity instance start \
--bind ./env-file.sh:/.singularity.d/env/env-file.sh \
--net \
--network static-redis \
--network-args "IP=192.168.20.12" \
--hostname redis1 \
--writable-tmpfs \
./redis.sif redis1
ERROR:   container cleanup failed: no instance found with name redis1
FATAL:   container creation failed: invalid CIDR 192.168.20.12: invalid CIDR address: 192.168.20.12

FATAL:   failed to start instance: while running /usr/local/libexec/singularity/bin/starter: exit status 255
```

checking list of instance running:
```
$> singularity instance list
INSTANCE NAME    PID    IP    IMAGE
```

checking network list **after** singularity command:
```
$> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:e5:1b:70:f4:63 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 85125sec preferred_lft 85125sec
    inet6 fe80::e5:1bff:fe70:f463/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:01:93:68 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.222/24 brd 192.168.111.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe01:9368/64 scope link
       valid_lft forever preferred_lft forever
#THIS IS THE NEW ENTRY ADDED
184: ssr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 96:b8:c3:95:1c:65 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::208a:1eff:fe11:7170/64 scope link
       valid_lft forever preferred_lft forever
```

**Expected behavior**
The singularity instance should start

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Installation Method**
I've installed Ubuntu in Virtualbox using vagrant and ansible and installed singularity with [abims_sbr.singularity](https://github.com/abims-sbr/ansible-singularity) role. Here is the relevant part:

```yaml
---
- name: Install singularity
  include_role:
    name: abims_sbr.singularity
    apply:
      become: true
      become_user: "{{ privileged_username | default(root) }}"

- include_tasks: configure_singularity_network.yml
```

**Additional context**
nothing at the moment

Am I missing something?

Thank you
